services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/dockers/jellyfin/config:/config
      - /opt/dockers/jellyfin/cache:/cache
      - /midia:/data/midias
    ports:
      - 8096:8096
    restart: unless-stopped
